version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_HTTP_PORTS=8070
      - ASPNETCORE_HTTPS_PORTS=8071
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro